# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5375a91b5679b41ea1c6b390c10be65ef36d1610587f02e8d9b7ffe231c81d95f91280601f77a998852abc76114a4f44f122bdb38ac3888dae1fc18e9959bdcc

test:
  secret_key_base: 10c0a5680ae9ff57ae539ddb129297284b1b8446fef7ec4b24da764db1f6f9be22d1bef900ad46d34b608dade775c6bc58409e1c905fc61366240dff25828ba5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
